name: scouting_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  http:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bottom_navy_bar: ^6.0.0
  

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/newlogo.png"


  flutter_lints: ^2.0.0




flutter:




  uses-material-design: true

 

  assets: 
    - assets/images/Logo.png
    - assets/images/add.png
    - assets/images/back.png

  